- name: 'Deploy gcp vm'
  hosts: localhost
  become: true
  gather_facts: no

  vars: 
    gcp_project: "kubernetes-adm"
    gcp_cred_kind: "serviceaccount"
    service_account_email: "752774956482-compute@developer.gserviceaccount.com"
    #gcp_cred_file: "/home/suryachandrakumar5/service-cred.json"
    gcp_cred_file: "/home/suryachandrakumar5/service-cred.json"
    gcp_region: "us-central1"
    gcp_zone: "us-central1-a"


  # Roles & Tasks
  tasks:

  - name: create a disk
    gcp_compute_disk:
      name: devops-casestudy-2
      size_gb: 50
      source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts
      zone: "{{ gcp_zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: disk

  - name: create a network
    gcp_compute_network:
      name: devops-casestudy-2
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: network

  - name: create a address
    gcp_compute_address:
      name: devops-casestudy-2
      region: "{{ gcp_region }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: address

  - name: create a instance
    gcp_compute_instance:
      name: devops-casestudy-2
      project: "{{ gcp_project }}"
      zone: "{{ gcp_zone }}"
      machine_type: n1-standard-1
      disks:
      - auto_delete: 'true'
        boot: 'true'
        source: "{{ disk }}"
      labels:
        environment: testing
      network_interfaces:
      - network: "{{ network }}"
        access_configs:
        - name: External NAT
          nat_ip: "{{ address }}"
          type: ONE_TO_ONE_NAT
      auth_kind: serviceaccount
      service_account_file: "{{ gcp_cred_file }}"
      state: present
